### ISSUE TITLE
Feature Request: Unlock charge cable

### ISSUE THREAD

**Issue by Jn115759** [yoziru/esphome-tesla-ble#100]
Would be very helpfull if you could unlock the charge cable via BLE after a load session.
Pls add this to the "controls" if possible

**Comment by mr-p666** [comment]
@Jn115759, you know that your Tesla automatically relocks the cable again after about a minute?!

**Comment by Jn115759** [comment]
@mr-p666 , thank you for this valuable information. I didn't know. I will close this request
