### ISSUE TITLE
Failed to download manifest

### ISSUE THREAD

**Issue by PedroKTFC** [yoziru/esphome-tesla-ble#16]
I tried to install using the link at https://yoziru.github.io/esphome-tesla-ble/ but I got the error `Failed to download manifest`. Any idea what I'm doing wrong? Thanks

**Comment by AntoineWaes9359** [comment]
Same issue here, trying to compile manually instead waiting for the fix .. :)

**Comment by yoziru** [comment]
Solved in https://github.com/yoziru/esphome-tesla-ble/commit/c2198fd6ceee998c710fa1a275cd6e19adf9c58e
