### ISSUE TITLE
Instructions not clear when using web flasher.

### ISSUE THREAD

**Issue by turbo2ltr** [yoziru/esphome-tesla-ble#25]
What is the purpose of this:

> If you have a supported device, you can also flash the latest version of the image by using Chrome, connecting your ESP32 through USB and going to https://yoziru.github.io/esphome-tesla-ble/

If you need to provide the secrets information before  you build the package?  Is there a way to edit it after  you flash it using the method above?

**Comment by yoziru** [comment]
Removed in https://github.com/yoziru/esphome-tesla-ble/pull/29/commits/15424b0deda28c6aae0340a698b2c7ae65a4f619, since you will need to compile your own version with your VIN and BLE MAC address (secrets.yaml)
