### ISSUE TITLE
Issue when compiling - ERROR: Cannot install esp-idf-kconfig==1.4.2 and esp-idf-kconfig==1.4.3 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by Jn115759** [yoziru/esphome-tesla-ble#86]
Hope someone is able to help me with this magnificent solution to control my Tesla.

I am using a M5Stack NanoC6 as recommended by @yoziru .
I am using the default set of yaml files posted in github, installing via Esphome Command Line.

During installation, I get the above error message.
Anyone an idea what needs to be changed/what I am doing wrong?

![image](https://github.com/user-attachments/assets/3fbe0d71-a8dd-4585-9910-9d9f089ee903)
![image](https://github.com/user-attachments/assets/5b5a53d8-8f88-45b6-955a-37d21c86559f)

**Comment by pvmil** [comment]
I use this same device, my config is in https://github.com/yoziru/esphome-tesla-ble/issues/70 , possibly that is of help. I do use this using the Home Assistant ESPHome interface though

**Comment by Jn115759** [comment]
> I use this same device, my config is in #70 , possibly that is of help. I do use this using the Home Assistant ESPHome interface though

Thanks you for helping out. I wil give it a try later today. 
I think the m5stack nanoc6 is not officially supported by esphome. 
Did you keep the references to this mcu in your configuration?
-   board: esp32-c6-devkitm-1
-   variant: esp32c6
-   flash_size: 4MB

Would be nice if you could post your complete yaml

**Comment by Jn115759** [comment]
[pvmil](https://github.com/pvmil) helped me a lot!. Thanks. I got it working.
Let me briefly specify how I did it (at the end...) using the Home Assistant ESPHome interface.

- connect your M5Stack NanoC6 with a USB data cable with the PC
- open ESPHOME in HA
- select "new device", press "continue" and give the device a (temporary) name (e.g. 'TeslaBLE')
- install initially as a "ESP32" and press "install" (you can't select 'esp32-c6' since this board is currently not supported)
- ensure the required secrets are defined (see secrets.yaml.example in the github repo)
- once installed, edit the yaml file and replace with the yaml code below
- select "install" and choose "plug into this computer"
- esphome will now compile the new code ("prepare download") - be patient.
- when finished, download the '.bin' file on your computer
- then select "open ESPhome web" and connect with the device
- choose "install",  select the '.bin' file and select "install"
- at the end, a new device should be ready in HA to be integrated (via "settings" --> "integrations"  

Hope this works for you.


`external_components:
  source: github://yoziru/esphome-tesla-ble/packages/external_components.dashboard.yml@main

packages:
  base:
    url: https://github.com/yoziru/esphome-tesla-ble/
    ref: main
    files: packages/base.yml
  device_base:
    url: https://github.com/yoziru/esphome-tesla-ble/
    ref: main
    files: boards/m5stack-nanoc6.yml
  client:
    url: https://github.com/yoziru/esphome-tesla-ble/
    ref: main
    files: packages/client.yml

dashboard_import:
  package_import_url: github://yoziru/esphome-tesla-ble/tesla-ble-m5stack-nanoc6.dashboard.yml`
